#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/git_scripts'

class Logger
  def self.puts(message)
    @messages = [] unless defined? @messages
    @messages << message.to_s
  end

  def self.to_s
    @messages.join("\n")
  end
end

def cherry_pick_pull_requests(jira_title)
  # TODO: maybe send the token?
  head = cherry_pick_branch(jira_title)
  create_branch(head)

  Logger.puts "Created a cherry-pick branch #{head}"

  prs = GitScripts::GitHub.new
    .merged_pull_requests(jira_title)
    .sort_by(&:merged_at)

  Logger.puts 'Cherry-picking the following PRs (in ascending order of merge date):'

  prs
    .each_with_index { |pr, index| Logger.puts "#{index}.\t#{pr.title}" }
    .each { |pr| cherry_pick(pr) }

  Logger.puts 'Opening Cherry-pick Pull Request'
  open_cherry_pick_pull_request(jira_title)
end

def cherry_pick(pull_request)
  execute "git cherry-pick -m 1 #{pull_request.merge_commit}"
end

def open_cherry_pick_pull_request(jira_title, branch)
  repo = 'https://github.com/tr/digital_emcm-web'
  base = "refs/heads/#{RELEASE_BRANCH}"
  head = "refs/heads/#{branch}"
  title = title(jira_title)
  message = body(jira_title, '')

  result = GitScripts::GitHub.create_pull_request(repo, base, head, title, message)

  Logger.puts "PR opened at #{result.html_url}"
rescue StandardError => _e
  Logger.puts "Failed to open PR for the branch #{branch}"
end

def title(jira_title)
  "[#{jira_title}]: Cherry-pick into the #{RELEASE_BRANCH} Branch"
end

def body(jira_title, log)
  <<~BODY
    [#{jira_title}](https://jira.thomsonreuters.com/browse/#{jira_title}): Cherry-pick into the #{RELEASE_BRANCH} Branch

    #{log}
  BODY
end

def cherry_pick_branch(jira_title)
  "releases/cherry-picking/#{jira_title}/#{Random.rand(16)}"
end

def create_branch(head, base)
  execute "git branch #{head} #{base}"
end

def checkout_branch(head)
  execute "git checkout #{head}"
end

def execute(command)
  Logger.puts "Attempting: #{command}"
  `#{command}`
  # or system command
  # or exe command

  Logger.puts 'Success!'
rescue StandardError => _e
  Logger.puts 'Failed! Try again manually'
end

RELEASE_BRANCH = 'release'
JIRA_TITLE = ARGV[0]

if JIRA_TITLE.blank?
  puts 'The first argument should specify the Jira title'

  exit 1
end

begin
  cherry_pick_pull_requests(JIRA_TITLE)

  puts Logger.to_s
rescue StandardError => e
  puts 'Failed to Cherry-pick Pull Requests'
  puts Logger.to_s

  puts "Exception:\n#{e}"
end
