#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/git_scripts'

require 'active_support'
require 'active_support/core_ext'
require 'nokogiri'
require 'rest-client'
require 'base64'

SEMVER_REGEX = /\d+\.\d+\.(\d+)$/
RELEASE_BRANCH_REGEX = /^(\d+)\.(\d+)/
ENVIRONMENT_REGEX = /^dev|qa|uat|ppe|prod$/i

environment_string = ARGV[0].to_s.strip
if environment_string.match? ENVIRONMENT_REGEX
  version = GitScripts::Environment.latest_environment_version(environment_string)
  puts "releases/#{version}"

  exit 0
end

release_branch_string = ARGV[0].to_s.strip
unless release_branch_string.match? RELEASE_BRANCH_REGEX
  puts "Provide argument in the form of '<MAJOR>.<MINOR>'"

  exit 1
end

major, minor = release_branch_string.match(RELEASE_BRANCH_REGEX)[1..2]
releases_branch = "releases/#{major}.#{minor}"
origin_releases_branch = "origin/#{releases_branch}"

GitScripts::Git.fetch_origin

result = `git branch --list --remote`
  .split("\n")
  .map(&:strip)
  .select { |item| item.start_with? origin_releases_branch }
  .map { |item| item.gsub("#{origin_releases_branch}.", '') }
  .map(&:to_i)

patch = Array(result).max

latest_release_branch = "#{releases_branch}.#{patch}"

puts latest_release_branch
