#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/git_scripts'

PAT = ''

username = Git.username
branch = ARGV[0] || Git.branch_name

github = GitHub.new(username, PAT)
my_pull_requests = github.my_pull_requests(branch)
# binding.pry

my_pull_requests.each do |item|
  # binding.pry
  puts item.html_url
end
