#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/git_scripts'

def list_pull_requests
  GitScripts::GitHub.new.jira_keys(REMOTE)
end

REMOTE = 'https://github.com/tr/digital_emcm-web.git'
puts list_pull_requests.join("\n")
