#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/git_scripts'

def my_pull_requests_url
  "#{GitScripts::Git.repo_url}/pulls/#{GitScripts::Git.username}"
end

puts my_pull_requests_url
